[Mode]
# 运行模式(debug: 调试, test: 测试, release: 正式)
RunMode = "debug"

[http]
# http 监听地址
Host = "127.0.0.1"
# http 监听端口
Port = 8080

[Log]
# 日志级别(-1: debug, 0: info, 1: warn, 2: error, 3: panic)
Level = 0
# 日志格式(支持输出格式：text/json)
Format = "json"
# 日志输出(支持：stdout/stderr/file)
Output = "stdout"
# 日志文件
Lowfile = "./temp/low.log"
Highfile = "./temp/high.log"
