basePath: /api/v1
definitions:
  error.ResponseNormal:
    properties:
      code:
        description: 响应状态码
        type: integer
      data:
        description: 返回内容
      msg:
        description: 返回消息
        type: string
    type: object
  schema.AddExam:
    properties:
      name:
        type: string
      student:
        items:
          type: string
        type: array
    type: object
  schema.AddQuestion:
    properties:
      content:
        type: string
      degree:
        type: integer
      io:
        items:
          $ref: '#/definitions/schema.TestData'
        type: array
      tag:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  schema.AddQuestionToExam:
    properties:
      exam_id:
        type: integer
      id:
        items:
          type: integer
        type: array
    type: object
  schema.Answer:
    properties:
      answer:
        type: string
      id:
        type: integer
    type: object
  schema.TestData:
    properties:
      input:
        type: string
      output:
        type: string
    type: object
  schema.UserLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  schema.UserRegister:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
      verify_code:
        type: string
    type: object
info:
  contact: {}
  description: This is a backend server for sylu-oj.
  title: sylu-oj
  version: "1.0"
paths:
  /exam/add_exam:
    post:
      consumes:
      - application/json
      description: 创建实验
      parameters:
      - description: exam message
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.AddExam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /exam/add_question:
    post:
      consumes:
      - application/json
      description: 添加题目到实验
      parameters:
      - description: exam id and question id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.AddQuestionToExam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /exam/detail:
    get:
      consumes:
      - application/json
      description: 查看实验具体信息
      parameters:
      - description: exam id
        in: query
        name: eid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /exam/inspect:
    get:
      consumes:
      - application/json
      description: 检查实验内题目的完成度
      parameters:
      - description: exam id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /exam/list:
    get:
      consumes:
      - application/json
      description: 查看有关当前用户的全部实验
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: integer
      - description: number per page
        in: query
        name: number
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /question/add_question:
    post:
      consumes:
      - application/json
      description: 发布题目
      parameters:
      - description: question message
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.AddQuestion'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /question/commit_answer:
    post:
      consumes:
      - application/json
      description: 查看题目详情
      parameters:
      - description: commit your answer of question
        in: body
        name: answer
        required: true
        schema:
          $ref: '#/definitions/schema.Answer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /question/del:
    delete:
      consumes:
      - application/json
      description: 删除题目
      parameters:
      - description: question id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /question/get_question_msg:
    get:
      consumes:
      - application/json
      description: 查看题目详情
      parameters:
      - description: get question message
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /question/list:
    get:
      consumes:
      - application/json
      description: 查看题目列表
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: number
      - description: rows per page
        in: query
        name: number
        required: true
        type: number
      - description: question title
        in: query
        name: search_title
        type: string
      - description: question tag
        in: query
        name: search_tag
        type: string
      - description: question degree
        in: query
        name: search_degree
        type: number
      - description: reorder
        in: query
        name: order
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /test/ping:
    get:
      consumes:
      - application/json
      description: 测试连接
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
      summary: 测试接口
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: user message
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /user/logout:
    get:
      consumes:
      - application/json
      description: 退出登录
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: user message
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
  /utils/email_verify:
    get:
      consumes:
      - application/json
      description: 发送邮箱验证码
      parameters:
      - description: user email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.ResponseNormal'
      summary: 邮箱验证接口
swagger: "2.0"
